### ISSUE TITLE
Android & Quest 2 Target Platforms Support?

### ISSUE THREAD

**Issue by walid-chekkouri** [millicast/millicast-publisher-unreal-engine-plugin#13]
I noticed that the plugin documentation states that the plugin is supported for Windows & Linux, can I also use it on an Android/Quest 2 project made in Unreal? If not when can this be supported?
Thanks

**Comment by dbaldassi** [comment]
We do not support it for android yet. We plan to do it. but I don't have an ETA for this.

**Comment by WalidCHEKKOURI** [comment]
I understand @dbaldassi , we have a project currently that we're working on for the Quest 2 platform so if there's anything that Dolby can do to help us it would be much appreciated, especially that Millicast already supports Android but with other technologies like Flutter, it would be very helpful for us to have a fully fledge product since were are currently in an advance stage of our prototype & hopefully soon with the help of Millicast can start.
If you need any further info feel free to reach out to me since I'm currently the engineer in our team.

Have a good week!

**Comment by dbaldassi** [comment]
The plugin now supports Android
