### ISSUE TITLE
Issues adding the plugin v1.7.0 to UE 5.3.2 on MacOS

### ISSUE THREAD

**Issue by jamiemarkwhite** [millicast/millicast-publisher-unreal-engine-plugin#61]
Hi, I am having problems with the plugin (v1.7.0) with UE 5.3.2 on MacOS (Apple M1 Pro). I can add and enable the plugin in the plugins list, and even after a restart of UE I do not see the "Millicast Publisher Source" asset in the media list (as shown in below screenshot). I also checked the source of the MillicastPublisher.uplugin and it doesn't appear that Mac is whitelisted anywhere. I even tried experimenting removing the white list, and also adding Mac to the white list - which in both scenarios shows [this prompt](https://github.com/millicast/millicast-publisher-unreal-engine-plugin/assets/2324594/1e5719f7-ff26-4d41-8d06-97844ab8baab) - but it fails to rebuild at that point.

Any help would be really appreciated.

Thanks

![Screenshot 2023-12-07 at 12 54 07](https://github.com/millicast/millicast-publisher-unreal-engine-plugin/assets/2324594/334a7702-3e7a-45a7-b88d-64474f00935d)

**Comment by dbaldassi** [comment]
Hi, we are currently fixingthe build for mac and adding support for ios and android as well.
There were a few changes in the plugin and the mac build was not updated.

But basically you need to download our WebRTC library to use it instead of the unreal one (that is not shipped on mac), that you can find on the unreal player download artifact and add it to the Plugin. It is documented how to do it on the player plugin readme, but we will update the documentation here too.

I will let you know when the new release will come out (likely in a few days) that will fix this issue.

**Comment by jamiemarkwhite** [comment]
HI, I got a little further with the CLI build when I added the architecture flag, but it unfortunately still failed: 

`-Architecture_Mac=arm64`

**Comment by dbaldassi** [comment]
Hi, I have just publish a release that fixed a few things on m1 and an updated libwebrtc build 
https://github.com/millicast/millicast-publisher-unreal-engine-plugin/releases/download/1.8.0/ThirdParty.zip
Let me know if you still have the build issue with it. Also did you try to build through the editor and get the same build issue ?

**Comment by dbaldassi** [comment]
For my environment, I usually build though xcode editor, with xcode 14.3.
